server:
  port: 9000

spring:
  application:
    name: homepage-zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
zuul:
  prefix: /kai
  routes:
    course:
      path: /homepage-course/**
      serviceId: eurake-client-homepage-course
      strip-prefix: false
    user:
      path: /homepage-user/**
      serviceId: eurake-client-homepage-user
      strip-prefix: false
