server:
  port: 7000
  servlet:
    context-path: /homepage-user
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: eurake-client-homepage-user
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://127.0.0.1/wangkai?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/


feign:
  hystrix:
    enabled: true
